apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: development-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      Environment: development
      Owner: Sam
      Name: development-vpc
    instanceTenancy: default
  providerConfigRef:
    name: awsconfig
