apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: development-internetgateway
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: development-vpc
  providerConfigRef:
    name: awsconfig

--- 

apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: development-routetable
spec:
  forProvider:
    region: us-east-1
    tags:
      Name: main-development-routetable
    vpcIdRef:
      name: development-vpc
  providerConfigRef:
    name: awsconfig

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: route
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: development-internetgateway
    region: us-east-1
    routeTableIdRef:
      name: development-routetable
  providerConfigRef:
    name: awsconfig

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-routetable-association-1
spec:
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: development-routetable
    subnetIdRef:
      name: dev-subnet-1
  providerConfigRef:
    name: awsconfig

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-routetable-association-2
spec:
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: development-routetable
    subnetIdRef:
      name: dev-subnet-2
  providerConfigRef:
    name: awsconfig