---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: tekanaid-sample-instance
spec:
  forProvider:
    region: us-east-1
    ami: ami-0557a15b87f6559cf
    instanceType: t2.micro
    keyName: my-crossplane-key-pair
    vpcSecurityGroupIdSelector:
      matchLabels:
        selector: my-security-group
    tags:
      Name: tekanaid-sample-instance
  providerConfigRef:
    name: awsconfig
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: KeyPair
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: Requires a valid public key.
  name: my-crossplane-key-pair
spec:
  forProvider:
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb7fcDZfIG+SxuP5UsZaoHPdh9MNxtEL5xRI71hzMS5h4SsZiPGEP4shLcF9YxSncdOJpyOJ6OgumNSFWj2pCd/kqg9wQzk/E1o+FRMbWX5gX8xMzPig8mmKkW5szhnP+yYYYuGUqvTAKX4ua1mQwL6PipWKYJ1huJhgpGHrvSQ6kuywJ23hw4klcaiZKXVYtvTi8pqZHhE5Kx1237a/6GRwnbGLEp0UR2Q/KPf6yRgZIrCdD+AtOznSBsBhf5vqcfnnwEIC/DOnqcOTahBVtFhOKuPSv3bUikAD4Vw7SIRteMltUVkd/O341fx+diKOBY7a8M6pn81HEZEmGsr7rT sam@SamMac.local
    region: us-east-1
  providerConfigRef:
    name: awsconfig